export const UPLOAD_IMAGE_REQUEST = "UPLOAD_IMAGE_REQUEST";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_FAIL = "UPLOAD_IMAGE_FAIL";

export const GET_SINGLE_IMAGE_REQUEST = "GET_SINGLE_IMAGE_REQUEST";
export const GET_SINGLE_IMAGE_SUCCESS = "GET_SINGLE_IMAGE_SUCCESS";
export const GET_SINGLE_IMAGE_FAIL = "GET_SINGLE_IMAGE_FAIL";

export const DELETE_IMAGE_REQUEST = "DELETE_IMAGE_REQUEST";
export const DELETE_IMAGE_SUCCESS = "DELETE_IMAGE_SUCCESS";
export const DELETE_IMAGE_FAIL = "DELETE_IMAGE_FAIL";
